version: '3'
services:

  promotions-main:
    build:
      context: ./
    ports:
      - "3030:3030"
    networks:
      - net

  promotions-mongo:
    image: mongo:latest
    container_name: promotions-mongo
    ports:
      - "27017:27017"
    networks:
      - net

networks:
    net: